---
title: "Overview of the tb3462a Package"
author: "Thomas Bilintoh"
date: "2020-01-28"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
`tb3462a` is the second package I am developing for the coursework componenet of GEOG346 (GEOSPATIAL Analysis with R).

It is currently a function called `mycalc` and executed as
follows:
```{r, error = TRUE}
library(tb346a2)

set.seed(1)
v1 <- sample(0:100, 20, replace=T)
v1
v2 <- sample(1:10, 20, replace=T)
v2
v3 <- runif(20, min = 0, max = 1)
v3
v4 <- as.character(names(v2) <- sample(LETTERS[1:20]))
v4
m1<- cbind(v1,v2)
m1
m2<- cbind(v2,v3)
m2
m3<- cbind(v3,v4)

m3 <- (m3)

DF<- data.frame(v1,v2,v3,v4)
DF
colnames(DF) <- c( "a", "b", "c", "grp")
DF


d1 <- mycalc(v1, v2, "sum")
d1
d2 <- mycalc(v2, v3, "sum")
d2
d3 <- mycalc(v1, v3, "sum")
d3
d4 <- mycalc(m1, m1, "sum")
d4
d5 <- mycalc(m1,m2,"sum")
d5
d6 <- mycalc(m2, m3, "sum")
d6

s1 <- mycalc(v1, v2, "divide")
s1
s2 <- mycalc(v2, v3, "divide")
s2
s3 <- mycalc(v1, v3, "divide")
s3
s4 <- mycalc(m1, m1, "divide")
s4
s5 <- mycalc(m1, m2, "divide")
s5
s6 <- mycalc(m2, m3, "divide")
s6


df_mult_1 <- mycalc(x=DF[1,1], y=DF[1,2], "multiply")
df_mult_1

df_mult_2 <- mycalc(x=DF[1:10,1:3], y=DF[1:10,1:3], "multiply")
df_mult_2

df_div_1 <- mycalc(x=DF[which(DF$grp%in%c("E")),]$a, y=DF[which(DF$grp%in%c("E")),]$b, "divide")
df_div_1

df_div_2 <- mycalc(x=DF[which(DF$grp%in%c("E")),]$a, y=DF[which(DF$grp%in%c("E")),]$c, "divide")
df_div_2

DF_div_1 <- DF[which(DF$grp%in%c("E")),]$a / DF[which(DF$grp%in%c("E")),]$b
DF_div_1

DF_div_2 <- DF[which(DF$grp%in%c("E")),]$a / DF[which(DF$grp%in%c("E")),]$c
DF_div_2

l <- list(v1,m1,m2)
l

l_sum<- lapply(l, sum)
l_sum 

k <- lapply(1:length(l),function(x){
  mycalc(l[[x]],v2,"multiply")
})
k

q <- sapply(1:length(l),function(x){
  mycalc(l[[x]],v2,"multiply")
})
q


```

I will be adding others, and updating this vignette as we go.

```{r}

```

